onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /testbench/NSYSRESET
add wave -noupdate /testbench/SYSCLK
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/DRV_TDO
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/EXT_RESETN
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/IRQ
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MEM_AXI_0_AR_BITS_ADDR
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MEM_AXI_0_AR_BITS_BURST
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MEM_AXI_0_AR_BITS_CACHE
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MEM_AXI_0_AR_BITS_ID
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MEM_AXI_0_AR_BITS_LEN
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MEM_AXI_0_AR_BITS_LOCK
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MEM_AXI_0_AR_BITS_PROT
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MEM_AXI_0_AR_BITS_QOS
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MEM_AXI_0_AR_BITS_SIZE
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MEM_AXI_0_AR_READY
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MEM_AXI_0_AR_VALID
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MEM_AXI_0_AW_BITS_ADDR
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MEM_AXI_0_AW_BITS_BURST
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MEM_AXI_0_AW_BITS_CACHE
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MEM_AXI_0_AW_BITS_ID
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MEM_AXI_0_AW_BITS_LEN
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MEM_AXI_0_AW_BITS_LOCK
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MEM_AXI_0_AW_BITS_PROT
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MEM_AXI_0_AW_BITS_QOS
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MEM_AXI_0_AW_BITS_SIZE
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MEM_AXI_0_AW_READY
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MEM_AXI_0_AW_VALID
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MEM_AXI_0_B_BITS_ID
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MEM_AXI_0_B_BITS_RESP
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MEM_AXI_0_B_READY
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MEM_AXI_0_B_VALID
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MEM_AXI_0_R_BITS_DATA
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MEM_AXI_0_R_BITS_ID
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MEM_AXI_0_R_BITS_LAST
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MEM_AXI_0_R_BITS_RESP
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MEM_AXI_0_R_READY
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MEM_AXI_0_R_VALID
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MEM_AXI_0_W_BITS_DATA
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MEM_AXI_0_W_BITS_LAST
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MEM_AXI_0_W_BITS_STRB
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MEM_AXI_0_W_BITS_WID
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MEM_AXI_0_W_READY
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MEM_AXI_0_W_VALID
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MEM_AXI_WID
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MMIO_AXI_0_AR_BITS_ADDR
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MMIO_AXI_0_AR_BITS_BURST
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MMIO_AXI_0_AR_BITS_CACHE
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MMIO_AXI_0_AR_BITS_ID
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MMIO_AXI_0_AR_BITS_LEN
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MMIO_AXI_0_AR_BITS_LOCK
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MMIO_AXI_0_AR_BITS_PROT
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MMIO_AXI_0_AR_BITS_QOS
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MMIO_AXI_0_AR_BITS_SIZE
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MMIO_AXI_0_AR_READY
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MMIO_AXI_0_AR_VALID
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MMIO_AXI_0_AW_BITS_ADDR
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MMIO_AXI_0_AW_BITS_BURST
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MMIO_AXI_0_AW_BITS_CACHE
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MMIO_AXI_0_AW_BITS_ID
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MMIO_AXI_0_AW_BITS_LEN
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MMIO_AXI_0_AW_BITS_LOCK
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MMIO_AXI_0_AW_BITS_PROT
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MMIO_AXI_0_AW_BITS_QOS
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MMIO_AXI_0_AW_BITS_SIZE
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MMIO_AXI_0_AW_READY
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MMIO_AXI_0_AW_VALID
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MMIO_AXI_0_B_BITS_ID
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MMIO_AXI_0_B_BITS_RESP
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MMIO_AXI_0_B_READY
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MMIO_AXI_0_B_VALID
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MMIO_AXI_0_R_BITS_DATA
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MMIO_AXI_0_R_BITS_ID
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MMIO_AXI_0_R_BITS_LAST
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MMIO_AXI_0_R_BITS_RESP
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MMIO_AXI_0_R_READY
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MMIO_AXI_0_R_VALID
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MMIO_AXI_0_W_BITS_DATA
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MMIO_AXI_0_W_BITS_LAST
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MMIO_AXI_0_W_BITS_STRB
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MMIO_AXI_0_W_BITS_WID
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MMIO_AXI_0_W_READY
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MMIO_AXI_0_W_VALID
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/MMIO_AXI_WID
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/RESETN
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/TCK
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/TDI
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/TDO
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/TMS
add wave -noupdate /testbench/MIV_RV32IMA_L1_AXI_0/TRST
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {102113149752 fs} 0}
quietly wave cursor active 1
configure wave -namecolwidth 243
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 fs} {990562592822 fs}
